# Generated by Django 3.2.9 on 2022-09-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donetask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('uid', models.IntegerField(max_length=50)),
                ('tname', models.CharField(max_length=500)),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('tdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('uid', models.IntegerField(max_length=50)),
                ('tname', models.CharField(max_length=500)),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('tdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('password', models.DateField()),
            ],
        ),
    ]
