# Generated by Django 3.2.9 on 2022-09-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tdate',
        ),
    ]
