# Generated by Django 3.2.9 on 2022-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='nid',
        ),
    ]
